# Generated by Django 3.1.4 on 2020-12-03 05:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contactinfosettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfosettings',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter the phone number you want your customers to contact you at.', max_length=128, region=None),
        ),
    ]
