# Generated by Django 3.1.4 on 2020-12-03 05:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('base', '0004_auto_20201203_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter the phone number you want your customers to contact you or your business through.', max_length=128, region=None)),
                ('email', models.EmailField(help_text="Enter the email you'd like customers to contact you / your business through.", max_length=254)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ContactInfoSettings',
        ),
    ]
