# Generated by Django 3.1.4 on 2020-12-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('base', '0005_auto_20201203_0742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessContactInfo',
            new_name='BusinessInformation',
        ),
    ]
