# Generated by Django 3.1.4 on 2020-12-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201203_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='phone_number_display',
            field=models.CharField(blank=True, help_text="Enter the phone number in the format you'd like your customers to see it (e.g., +1 (303) 261-8653)", max_length=20),
        ),
    ]
