# Generated by Django 3.1.4 on 2020-12-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20201203_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='email_display',
            field=models.CharField(blank=True, help_text="Enter the email or text you'd like people to see & click on. (defaults to Email set above if none).", max_length=50),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='phone_number_display',
            field=models.CharField(blank=True, help_text="Enter the phone number in the format you'd like your customers to see it (e.g., +1 (303) 261-8653)", max_length=50),
        ),
    ]
