# Generated by Django 3.1.4 on 2020-12-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20201203_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='main_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_cta_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=260),
        ),
    ]
