# Generated by Django 3.1.4 on 2020-12-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('base', '0010_auto_20201203_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='main_cta_link',
            new_name='hero_cta_link',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='main_cta_text',
            new_name='hero_cta_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='subtitle',
            new_name='hero_subtitle',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=260),
        ),
    ]
