# Generated by Django 3.1.4 on 2020-12-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20201203_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.CharField(blank=True, max_length=260),
        ),
    ]
