# Generated by Django 3.1.4 on 2020-12-03 14:34

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20201203_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.CharField(blank=True, max_length=260, verbose_name='Hero CTA link'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hero CTA text'),
        ),
    ]
